version: '3.1'

services:
  apache:
    image: httpd:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    networks: 
      - frontend
      - backend
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql
  php:
    build: './php'
    restart: always
    networks: 
      - backend
    volumes:
      - ./public_html:/usr/local/apache2/htdocs
      - ./tmp:/usr/local/tmp
  mysql:
    build: './mysql'
    restart: always
    networks:
      - backend
    volumes:
      - ./database:/var/lib/mysql
  nodejs:
    
networks: 
  backend:
  frontend:
